# Cloud Build config to build and push the container image
# Requires substitutions _REGION, _SERVICE, _REPO, _WORKFLOW_ID   

substitutions:
  _REGION: europe-west1
  _SERVICE: agents-chatkit-v2
  _REPO: agentes-chatkit-v2
  _WORKFLOW_ID: "wf_68e8d36769c08190afd14b9c9281a7c6064da5bd359ab3ce"
  
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - .
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --build-arg
      - NEXT_PUBLIC_CHATKIT_WORKFLOW_ID=${_WORKFLOW_ID}
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
