# Cloud Build config to build and push the container image
# Requires substitutions _REGION, _SERVICE, _REPO

substitutions:
  _REGION: us-central1
  _SERVICE: chatkit-starter
  _REPO: chatkit-starter

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - .
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
