# Cloud Build config to build and push the container image
# Requires substitutions _REGION, _SERVICE, _REPO, _WORKFLOW_ID 

substitutions:
  _REGION: europe-west1
  _SERVICE: agents-chatkit-v2
  _REPO: agentes-chatkit-v2
  _WORKFLOW_ID: "wf_68ee77a70ce08190a75e19e9b0a4f27f094b95735d6ec6b3"
  
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - .
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --build-arg
      - NEXT_PUBLIC_CHATKIT_WORKFLOW_ID=${_WORKFLOW_ID}
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
